### ISSUE TITLE
Feedback milestone 3 from group session

### ISSUE THREAD

**Issue by K3ra-y** [UBC-MDS/DSCI_532-boston-crime-rate#26]
Feedback from [Juno Chen](https://github.com/huijuechen) and [Kera Yucel](https://github.com/K3ra-y)

- [ ] Delete "Menu options".

- [ ]  Add hover on functionality to the map, showing the region and the density.

- [ ] Change Boston crime density from scale of colors using dark to light color. 

- [ ] Add name of district to bar chart.

- [ ] Change x and y axis labels with more explanation.

**Comment by hfboyce** [comment]
Thank you for all your feedback. 
We have addressed the majority of these in #31. 
The items we have not addressed were addressed in our Milestone3 write up.
